<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\UndergroundBank.Common\UndergroundBank.Common.csproj" />
	  <ProjectReference Include="..\UndergroundBank.LoanService.Domain\UndergroundBank.LoanService.Domain.csproj" />
	</ItemGroup>


	<PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
