<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="AutoMapper" Version="14.0.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
	  <PackageReference Include="EasyNetQ" Version="7.8.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.13">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="Npgsql" Version="8.0.6" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
	  <PackageReference Include="Quartz" Version="3.13.1" />
	  <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
	  <PackageReference Include="OpenTelemetry" Version="1.7.0" />
	  <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.7.0" />
	  <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.7.0" />
	  <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.0.0-rc9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UndergroundBank.Common\UndergroundBank.Common.csproj" />
    <ProjectReference Include="..\UndergroundBank.LoanService.Application\UndergroundBank.LoanService.Application.csproj" />
    <ProjectReference Include="..\UndergroundBank.LoanService.Domain\UndergroundBank.LoanService.Domain.csproj" />
  </ItemGroup>

</Project>
