// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UndergroundBank.LoanService.Infrastructure;

#nullable disable

namespace UndergroundBank.LoanService.Infrastructure.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20250303171718_LoanInit")]
    partial class LoanInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UndergroundBank.LoanService.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("LoanDurationInMonth")
                        .HasColumnType("integer");

                    b.Property<decimal>("RemainingPayment")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("UndergroundBank.LoanService.Domain.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxLoanDuration")
                        .HasColumnType("integer");

                    b.Property<double>("MinAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("MinLoanDuration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("UndergroundBank.LoanService.Domain.Entities.Loan", b =>
                {
                    b.HasOne("UndergroundBank.LoanService.Domain.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tariff");
                });
#pragma warning restore 612, 618
        }
    }
}
