<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EasyNetQ" Version="7.8.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UndergroundBank.Common\UndergroundBank.Common.csproj" />
    <ProjectReference Include="..\UndergroundBank.NotificationService.Domain\UndergroundBank.NotificationService.Domain.csproj" />
  </ItemGroup>

</Project>
