{
 "title": "UnderGroundBank [Auth]",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "auth_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency p95 (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(auth_duration_ms_milliseconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100\r\n*\r\nsum(rate(auth_requests_total{status_code!=\"200\"}[5m]))\r\n/\r\nsum(rate(auth_requests_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency (Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(auth_duration_ms_milliseconds_sum[5m]))\r\n/\r\nsum(rate(auth_duration_ms_milliseconds_count[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"demo-python\"} |= ``"
    }
   ]
  },
  {
   "title": "Tempo Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "f715cd2d", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "demo-python" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}